package com.wayonsys.account.common.enums;

/**
 * Created by wayonsys on 2017/4/19.
 */
public enum FileType {

    ONE_TWO_THREE("123", "application/vnd.lotus-1-2-3"),
    THREE_DS("3ds", "image/x-3ds"),
    THREE_GP("3gp", "video/3gpp"),
    AAC("aac", "audio/mp4"),
    ABW("abw", "application/x-abiword"),
    AC_THREE("ac3", "audio/ac3"),
    ACE("ace", "application/x-ace"),
    ADB("adb", "text/x-adasrc"),
    ADS("ads", "text/x-adasrc"),
    AFM("afm", "application/x-font-afm"),
    AG("ag", "image/x-applix-graphics"),
    AI("ai", "application/illustrator"),
    AIF("aif", "audio/x-aiff"),
    AIFC("aifc", "audio/x-aiff"),
    AIFF("aiff", "audio/x-aiff"),
    AL("al","application/x-perl"),
    ALZ("alz","application/x-alz"),
    AMR("amr","audio/amr"),
    ANI("ani","application/x-navi-animation"),
    ANX("anx","application/annodex"),
    APE("ape","audio/x-ape"),
    ARJ("arj","application/x-arj"),
    ARW("arw","image/x-sony-arw"),
    AS("as","application/x-applix-spreadsheet"),
    ASC("asc","text/plain"),
    ASF("asf","video/x-ms-asf"),
    ASP("asp","application/x-asp"),
    ASS("ass","text/x-ssa"),
    ASX("asx","audio/x-ms-asx"),
    ATOM("atom","application/atom+xml"),
    AU("au","audio/basic"),
    avi("avi","video/x-msvideo"),
    AW("aw","application/x-applix-word"),
    AWB("awb","audio/amr-wb"),
    AWK("awk","application/x-awk"),
    AXA("axa","audio/annodex"),
    AXV("axv","video/annodex"),
    BAK("bak","application/x-trash"),
    BDF("bdf","application/x-font-bdf"),
    BIB("bib","text/x-bibtex"),
    BIN("bin","application/octet-stream"),
    BMP("bmp","image/bmp"),
    BZ("bz","application/x-bzip"),
    C("c","text/x-csrc"),
    C_PLUS("c++","text/x-c++src"),
    CAB("cab","application/vnd.ms-cab-compressed"),
    CBR("cbr","application/x-cbr"),
    CBT("cbt","application/x-cbt"),
    CBZ("cbz","application/x-cbz"),
    CC("cc","text/x-c++src"),
    CDF("cdf","application/x-netcdf"),
    CER("cer","application/x-x509-ca-cert"),
    CGM("cgm","image/cgm"),
    CLASS("class","application/x-java"),
    CLS("cls","text/x-tex"),
    CMAKE("cmake","text/x-cmake"),
    CPP("cpp","text/x-c++src"),
    CS("cs","text/x-csharp"),
    CSS("css","text/css"),
    CSS1("cssl","text/css"),
    CSV("csv","text/csv"),
    CUE("cue","application/x-cue"),
    D("d","text/x-dsrc"),
    DAR("dar","application/x-dar"),
    DC("dc","application/x-dc-rom"),
    DDS("dds","image/x-dds"),
    DESKTOP("desktop","application/x-desktop"),
    DOC("doc","application/msword"),
    DOCBOOK("docbook","application/docbook+xml"),
    DOCM("docm","application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    DOCX("docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
    DOT("dot","text/vnd.graphviz"),
    DS1("dsl","text/x-dsl"),
    DTD("dtd","application/xml-dtd"),
    DTX("dtx","text/x-tex"),
    DV("dv","video/dv"),
    DWG("dwg","image/vnd.dwg"),
    DXF("dxf","image/vnd.dxf"),
    E("e","text/x-eiffel"),
    EGON("egon","application/x-egon"),
    EL("el","text/x-emacs-lisp"),
    EMF("emf","image/x-emf"),
    EMP("emp","application/vnd.emusic-emusic_package"),
    ENT("ent","application/xml-external-parsed-entity"),
    EPS("eps","image/x-eps"),
    ES("es","application/ecmascript"),
    ETHEME("etheme","application/x-e-theme"),
    EXE("exe","application/x-ms-dos-executable"),
    EXR("exr","image/x-exr"),
    EZ("ez","application/andrew-inset"),
    F("f","text/x-fortran"),
    FIG("fig","image/x-xfig"),
    FITS("fits","image/fits"),
    FLAC("flac","audio/x-flac"),
    FLC("flc","video/x-flic"),
    FLV("flv","video/x-flv"),
    FO("fo","text/x-xslfo"),
    FOR("for","text/x-fortran"),
    G3("g3","image/fax-g3"),
    GBA("gba","application/x-gba-rom"),
    GF("gf","application/x-tex-gf"),
    GG("gg","application/x-sms-rom"),
    GIF("gif","image/gif"),
    GV("gv","text/vnd.graphviz"),
    GZ("gz","application/x-gzip"),
    H("h","text/x-chdr"),
    HDF("hdf","application/x-hdf"),
    HH("hh","text/x-c++hdr"),
    HP("hp","text/x-c++hdr"),
    HTM("htm","text/html"),
    HTML("html","text/html"),
    HXX("hxx","text/x-c++hdr"),
    ICA("ica","application/x-ica"),
    ICB("icb","image/x-tga"),
    ICNS("icns","image/x-icns"),
    ICO("ico","image/vnd.microsoft.icon"),
    ICS("ics","text/calendar"),
    IEF("ief","image/ief"),
    ISO("iso","application/x-cd-image"),
    IT("it","audio/x-it"),
    J2K("j2k","image/jp2"),
    JAR("jar","application/x-java-archive"),
    JAVA("java","text/x-java"),
    JNG("jng","image/x-jng"),
    JP2("jp2","image/jp2"),
    JPE("jpe","image/jp2"),
    JPG("jpg","image/jpeg"),
    JPEG("jpeg","image/jpeg"),
    JS("js","application/javascript"),
    JSON("json","application/json"),
    JSONP("jsonp","application/jsonp"),
    KAR("kar","audio/midi"),
    KDC("kdc","image/x-kodak-kdc"),
    KFO("kfo","application/x-kformula"),
    KWD("kwd","application/x-kword"),
    KWT("kwt","application/x-kword"),
    LATEX("latex","text/x-tex"),
    LOG("log","text/x-log"),
    LTX("ltx","text/x-tex"),
    LUA("lua","text/x-lua"),
    LY("ly","text/x-lilypond"),
    M("m","text/x-matlab"),
    M4("m4","application/x-m4"),
    M4A("m4a","audio/mp4"),
    M4B("m4b","audio/x-m4b"),
    M4V("m4v","video/mp4"),
    ME("me","text/x-troff-me"),
    MID("mid","audio/midi"),
    MIDI("midi","audio/midi"),
    MKA("mka","audio/x-matroska"),
    MKV("mkv","video/x-matroska"),
    ML("ml","text/x-ocaml"),
    MM("mm","text/x-troff-mm"),
    MNG("mng","video/x-mng"),
    MOVIE("movie","video/x-sgi-movie"),
    MP2("mp2","video/mpeg"),
    MP3("mp3","audio/mpeg"),
    MP4("mp4","video/mp4"),
    MPC("mpc","audio/x-musepack"),
    MPE("mpe","video/mpeg"),
    MPEG("mpeg","video/mpeg"),
    MPG("mpg","video/mpeg"),
    MPGA("mpga","audio/mpeg"),
    NES("nes","application/x-nes-rom"),
    NSV("nsv","video/x-nsv"),
    O("o","application/x-object"),
    OBJ("obj","application/x-tgif"),
    OC1("oc1","text/x-ocl"),
    ODA("oda","application/oda"),
    ODB("odb","application/vnd.oasis.opendocument.database"),
    ODC("odc","application/vnd.oasis.opendocument.chart"),
    ODF("odf","application/vnd.oasis.opendocument.formula"),
    ODG("odg","application/vnd.oasis.opendocument.graphics"),
    ODI("odi","application/vnd.oasis.opendocument.image"),
    OGA("oga","audio/ogg"),
    OLD("old","application/x-trash"),
    OTF("otf","application/x-font-otf"),
    P("p","text/x-pascal"),
    PAK("pak","application/x-pak"),
    PAS("pas","text/x-pascal"),
    PDB("pdb","chemical/x-pdb"),
    PDF("pdf","application/pdf"),
    PEF("pef","image/x-pentax-pef"),
    PEM("pem","application/x-x509-ca-cert"),
    PHP("php","application/x-php"),
    PICT("pict","image/x-pict"),
    PICT1("pict1","image/x-pict"),
    PICT2("pict2","image/x-pict"),
    PK("pk","application/x-tex-pk"),
    PNG("png","image/png"),
    PNM("pnm","image/x-portable-anymap"),
    PPS("pps","application/vnd.ms-powerpoint"),
    PPT("ppt","application/vnd.ms-powerpoint"),
    PPZ("ppz","application/vnd.ms-powerpoint"),
    PS("ps","application/postscript"),
    PSD("psd","image/vnd.adobe.photoshop"),
    PSF("psf","audio/x-psf"),
    PSW("psw","application/x-pocket-word"),
    QT("qt","video/quicktime"),
    QTIF("qtif","image/x-quicktime"),
    QTVR("qtvr","video/quicktime"),
    RAM("ram","application/ram"),
    RAR("rar","application/x-rar"),
    RAS("ras","image/x-cmu-raster"),
    RAW("raw","image/x-panasonic-raw"),
    RB("rb","application/x-ruby"),
    RGB("rgb","image/x-rgb"),
    RLE("rle","image/rle"),
    RM("rm","application/vnd.rn-realmedia"),
    RMVB("rmvb","application/vnd.rn-realmedia"),
    RMJ("rmj","application/vnd.rn-realmedia"),
    RMM("rmm","application/vnd.rn-realmedia"),
    RMS("rms","application/vnd.rn-realmedia"),
    RMX("rmx","application/vnd.rn-realmedia"),
    ROFF("roff","text/troff"),
    RP("rp","image/vnd.rn-realpix"),
    S3M("s3m","audio/x-s3m"),
    SAM("sam","application/x-amipro"),
    SDD("sdd","application/vnd.stardivision.impress"),
    SK("sk","image/x-skencil"),
    SMAF("smaf","application/x-smaf"),
    SPX("spx","audio/x-speex"),
    SQL("sql","text/x-sql"),
    SR2("sr2","image/x-sony-sr2"),
    SRC("src","application/x-wais-source"),
    SRF("srf","image/x-sony-srf"),
    SSA("ssa","text/x-ssa"),
    SVG("svg","image/svg+xml"),
    SVGZ("svgz","image/svg+xml-compressed"),
    SWF("swf","application/x-shockwave-flash"),
    T("t","text/troff"),
    TAR("tar","application/x-tar"),
    TCL("tcl","ext/x-tcl"),
    TEX("tex","text/x-tex"),
    TGA("tga","image/x-tga"),
    TGZ("tgz","application/x-compressed-tar"),
    THEME("theme","application/x-theme"),
    TIF("tif","image/tiff"),
    TIFF("tiff","image/tiff"),
    TK("tk","text/x-tcl"),
    TTF("ttf","application/x-font-ttf"),
    TTC("ttc","application/x-font-ttf"),
    TTX("ttx","application/x-font-ttx"),
    TXT("txt","text/plain"),
    TXZ("txz","application/x-xz-compressed-tar"),
    UI("ui","application/x-designer"),
    UIL("uil","text/x-uil"),
    URI("uri","text/x-uri"),
    URL("url","text/x-uri"),
    VCF("vcf","text/directory"),
    VSC("vcs","text/calendar"),
    VCT("vct","text/directory"),
    VDA("vda","image/x-tga"),
    VIVO("vivo","video/vivo"),
    VIV("viv","video/vivo"),
    VOB("vob","video/mpeg"),
    VOC("voc","audio/x-voc"),
    VST("vst","image/x-tga"),
    WAV("wav","audio/x-wav"),
    WAX("wax","audio/x-ms-asx"),
    WB1("wb1","application/x-quattropro"),
    WB2("wb2","application/x-quattropro"),
    WB3("wb3","application/x-quattropro"),
    WK1("wk1","application/vnd.lotus-1-2-3"),
    WK3("wk3","application/vnd.lotus-1-2-3"),
    WK4("wk4","application/vnd.lotus-1-2-3"),
    WMA("wma","audio/x-ms-wma"),
    WMF("wmf","image/x-wmf"),
    WMV("wmv","video/x-ms-wmv"),
    WV("wv","audio/x-wavpack"),
    XBL("xbl","application/xml"),
    XBM("xbm","image/x-xbitmap"),
    XCF("xcf","image/x-xcf"),
    XLA("xla","application/vnd.ms-excel"),
    XLC("xlc","application/vnd.ms-excel"),
    XLD("xld","application/vnd.ms-excel"),
    XLL("xll","application/vnd.ms-excel"),
    XLM("xlm","application/vnd.ms-excel"),
    XLS("xls","application/vnd.ms-excel"),
    XLSM("xlsm","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    XLSX("xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
    XM("xm","audio/x-xm"),
    XMF("xmf","audio/x-xmf"),
    XMI("xmi","text/x-xmi"),
    XML("xml","application/xml"),
    XPS("xps","application/vnd.ms-xpsdocument"),
    XSL("xsl","application/xml"),
    XWD("xwd","image/x-xwindowdump"),
    XYZ("xyz","chemical/x-pdb"),
    Z("z","application/x-compress"),
    ZIP("zip","application/zip"),
    ZOO("zoo","application/x-zoo"),
    LOAD("load","text/html");

    private String name;
    private String type;

    FileType(String name, String type){
        this.name = name;
        this.type = type;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}
